# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/colin/Documents/PI-CNC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/colin/Documents/PI-CNC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/colin/Documents/PI-CNC/CMakeFiles /home/colin/Documents/PI-CNC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/colin/Documents/PI-CNC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pi-cnc

# Build rule for target.
pi-cnc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi-cnc
.PHONY : pi-cnc

# fast build rule for target.
pi-cnc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/build
.PHONY : pi-cnc/fast

clidisplay.o: clidisplay.cpp.o

.PHONY : clidisplay.o

# target to build an object file
clidisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/clidisplay.cpp.o
.PHONY : clidisplay.cpp.o

clidisplay.i: clidisplay.cpp.i

.PHONY : clidisplay.i

# target to preprocess a source file
clidisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/clidisplay.cpp.i
.PHONY : clidisplay.cpp.i

clidisplay.s: clidisplay.cpp.s

.PHONY : clidisplay.s

# target to generate assembly for a file
clidisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/clidisplay.cpp.s
.PHONY : clidisplay.cpp.s

gcode.o: gcode.cpp.o

.PHONY : gcode.o

# target to build an object file
gcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcode.cpp.o
.PHONY : gcode.cpp.o

gcode.i: gcode.cpp.i

.PHONY : gcode.i

# target to preprocess a source file
gcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcode.cpp.i
.PHONY : gcode.cpp.i

gcode.s: gcode.cpp.s

.PHONY : gcode.s

# target to generate assembly for a file
gcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcode.cpp.s
.PHONY : gcode.cpp.s

gcodeinterface.o: gcodeinterface.cpp.o

.PHONY : gcodeinterface.o

# target to build an object file
gcodeinterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeinterface.cpp.o
.PHONY : gcodeinterface.cpp.o

gcodeinterface.i: gcodeinterface.cpp.i

.PHONY : gcodeinterface.i

# target to preprocess a source file
gcodeinterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeinterface.cpp.i
.PHONY : gcodeinterface.cpp.i

gcodeinterface.s: gcodeinterface.cpp.s

.PHONY : gcodeinterface.s

# target to generate assembly for a file
gcodeinterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeinterface.cpp.s
.PHONY : gcodeinterface.cpp.s

gcodeparse.o: gcodeparse.cpp.o

.PHONY : gcodeparse.o

# target to build an object file
gcodeparse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeparse.cpp.o
.PHONY : gcodeparse.cpp.o

gcodeparse.i: gcodeparse.cpp.i

.PHONY : gcodeparse.i

# target to preprocess a source file
gcodeparse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeparse.cpp.i
.PHONY : gcodeparse.cpp.i

gcodeparse.s: gcodeparse.cpp.s

.PHONY : gcodeparse.s

# target to generate assembly for a file
gcodeparse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/gcodeparse.cpp.s
.PHONY : gcodeparse.cpp.s

globalcommunication.o: globalcommunication.cpp.o

.PHONY : globalcommunication.o

# target to build an object file
globalcommunication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/globalcommunication.cpp.o
.PHONY : globalcommunication.cpp.o

globalcommunication.i: globalcommunication.cpp.i

.PHONY : globalcommunication.i

# target to preprocess a source file
globalcommunication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/globalcommunication.cpp.i
.PHONY : globalcommunication.cpp.i

globalcommunication.s: globalcommunication.cpp.s

.PHONY : globalcommunication.s

# target to generate assembly for a file
globalcommunication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/globalcommunication.cpp.s
.PHONY : globalcommunication.cpp.s

iocontroller.o: iocontroller.cpp.o

.PHONY : iocontroller.o

# target to build an object file
iocontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/iocontroller.cpp.o
.PHONY : iocontroller.cpp.o

iocontroller.i: iocontroller.cpp.i

.PHONY : iocontroller.i

# target to preprocess a source file
iocontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/iocontroller.cpp.i
.PHONY : iocontroller.cpp.i

iocontroller.s: iocontroller.cpp.s

.PHONY : iocontroller.s

# target to generate assembly for a file
iocontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/iocontroller.cpp.s
.PHONY : iocontroller.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/main.cpp.s
.PHONY : main.cpp.s

positioncalc.o: positioncalc.cpp.o

.PHONY : positioncalc.o

# target to build an object file
positioncalc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/positioncalc.cpp.o
.PHONY : positioncalc.cpp.o

positioncalc.i: positioncalc.cpp.i

.PHONY : positioncalc.i

# target to preprocess a source file
positioncalc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/positioncalc.cpp.i
.PHONY : positioncalc.cpp.i

positioncalc.s: positioncalc.cpp.s

.PHONY : positioncalc.s

# target to generate assembly for a file
positioncalc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/positioncalc.cpp.s
.PHONY : positioncalc.cpp.s

programrun.o: programrun.cpp.o

.PHONY : programrun.o

# target to build an object file
programrun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/programrun.cpp.o
.PHONY : programrun.cpp.o

programrun.i: programrun.cpp.i

.PHONY : programrun.i

# target to preprocess a source file
programrun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/programrun.cpp.i
.PHONY : programrun.cpp.i

programrun.s: programrun.cpp.s

.PHONY : programrun.s

# target to generate assembly for a file
programrun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/programrun.cpp.s
.PHONY : programrun.cpp.s

stepper.o: stepper.cpp.o

.PHONY : stepper.o

# target to build an object file
stepper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/stepper.cpp.o
.PHONY : stepper.cpp.o

stepper.i: stepper.cpp.i

.PHONY : stepper.i

# target to preprocess a source file
stepper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/stepper.cpp.i
.PHONY : stepper.cpp.i

stepper.s: stepper.cpp.s

.PHONY : stepper.s

# target to generate assembly for a file
stepper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/stepper.cpp.s
.PHONY : stepper.cpp.s

vfdcontrol.o: vfdcontrol.cpp.o

.PHONY : vfdcontrol.o

# target to build an object file
vfdcontrol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/vfdcontrol.cpp.o
.PHONY : vfdcontrol.cpp.o

vfdcontrol.i: vfdcontrol.cpp.i

.PHONY : vfdcontrol.i

# target to preprocess a source file
vfdcontrol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/vfdcontrol.cpp.i
.PHONY : vfdcontrol.cpp.i

vfdcontrol.s: vfdcontrol.cpp.s

.PHONY : vfdcontrol.s

# target to generate assembly for a file
vfdcontrol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi-cnc.dir/build.make CMakeFiles/pi-cnc.dir/vfdcontrol.cpp.s
.PHONY : vfdcontrol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pi-cnc"
	@echo "... clidisplay.o"
	@echo "... clidisplay.i"
	@echo "... clidisplay.s"
	@echo "... gcode.o"
	@echo "... gcode.i"
	@echo "... gcode.s"
	@echo "... gcodeinterface.o"
	@echo "... gcodeinterface.i"
	@echo "... gcodeinterface.s"
	@echo "... gcodeparse.o"
	@echo "... gcodeparse.i"
	@echo "... gcodeparse.s"
	@echo "... globalcommunication.o"
	@echo "... globalcommunication.i"
	@echo "... globalcommunication.s"
	@echo "... iocontroller.o"
	@echo "... iocontroller.i"
	@echo "... iocontroller.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... positioncalc.o"
	@echo "... positioncalc.i"
	@echo "... positioncalc.s"
	@echo "... programrun.o"
	@echo "... programrun.i"
	@echo "... programrun.s"
	@echo "... stepper.o"
	@echo "... stepper.i"
	@echo "... stepper.s"
	@echo "... vfdcontrol.o"
	@echo "... vfdcontrol.i"
	@echo "... vfdcontrol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

